### ISSUE TITLE
empty mails every 5 minutes to all users

### ISSUE THREAD

**Issue by Canx** [dualcube/moodle-tool_inactive_user_cleanup#1]
I had to disable this plugin because it was flooding several of my users with emails every 5 minutes. I am using latest 3.0 moodle from repository. The stack trace from PHPMailer postSend() method was:

#0 /var/www/moodle/lib/phpmailer/class.phpmailer.php(1071): moodle_phpmailer->postSend()
#1 /var/www/moodle/lib/moodlelib.php(5672): PHPMailer->send()
#2 /var/www/moodle/admin/tool/inactive_user_cleanup/lib.php(45): email_to_user(Object(stdClass), Object(stdClass), false, \'\')
#3 /var/www/moodle/lib/cronlib.php(223): tool_inactive_user_cleanup_cron()
#4 /var/www/moodle/lib/classes/task/legacy_plugin_cron_task.php(162): cron_execute_plugin_type(\'tool\', \'admin tools\')
#5 /var/www/moodle/lib/cronlib.php(75): core\\task\\legacy_plugin_cron_task->execute()
#6 /var/www/moodle/admin/cli/cron.php(61): cron_run()

**Comment by parthajeet** [comment]
Hello Ruben,

We have updated our plugin with new fixes. You can try the latest update from moodle.org. Hope it will resolve the issue.

Regards,
Parthajeet~
