### ISSUE TITLE
background task stops with an error

### ISSUE THREAD

**Issue by corvus-albus** [dualcube/moodle-tool_inactive_user_cleanup#18]
We are using Moodle 4.3 and inactive_user_cleanup 2.7.2. 
The background task stops with an error:

> Execute scheduled task: Inaktive Bereinigung von Nutzerkonten (tool_inactive_user_cleanup\task\tool_inactive_user_cleanup_task)
> ... started 23:42:01. Current memory use 21.7 MB.
> Debugging increased temporarily due to faildelay of 480
> Hey, admin tool inactive user cleanup is running
> USER ID 
> 1687---xxx@web.de
> User is inactive for past day 1263
> ... used 755 dbqueries
> ... used 0.98191905021667 seconds
> Scheduled task failed: Inaktive Bereinigung von Nutzerkonten (tool_inactive_user_cleanup\task\tool_inactive_user_cleanup_task),Too few arguments to function mtrace(), 0 passed in /opt/moodle/git/admin/tool/inactive_user_cleanup/classes/task/tool_inactive_user_cleanup_task.php on line 70 and at least 1 expected
> Backtrace:
> * line 70 of /admin/tool/inactive_user_cleanup/classes/task/tool_inactive_user_cleanup_task.php: call to mtrace()
> * line 405 of /lib/classes/cron.php: call to tool_inactive_user_cleanup\task\tool_inactive_user_cleanup_task->execute()
> * line 208 of /lib/classes/cron.php: call to core\cron::run_inner_scheduled_task()
> * line 125 of /lib/classes/cron.php: call to core\cron::run_scheduled_tasks()
> * line 186 of /admin/cli/cron.php: call to core\cron::run_main_process()
> 

It would be really great, if we could  use this plugin. As more information is needed, I will provide it soon.

Cheers corvus-albus

**Comment by kndnsow** [comment]
Hello @corvus-albus,

We are unable to reproduce the error on our end, and everything appears to be working correctly. However, we suggest a potential solution to address the issue:

In line 70 of the file /admin/tool/inactive_user_cleanup/classes/task/tool_inactive_user_cleanup_task.php, please modify the mtrace() function call to mtrace(''). This change is a debugging step to investigate if it resolves the problem. If it does, we will consider implementing this change in the next update.

Please let us know if this modification helps in resolving the issue. If you have any further questions or need assistance, feel free to reach out. Thank you.

**Comment by corvus-albus** [comment]
Hello kndnsow,
really great, that did the trick. It works now!
Cheers corvus-albus
P.S. I'm unsure: Should I close the issue?
