### ISSUE TITLE
Namespace declaration statement

### ISSUE THREAD

**Issue by Snickser** [dualcube/moodle-tool_inactive_user_cleanup#19]
`
Fatal error: Namespace declaration statement has to be the very first statement or after any declare call in the script in /var/www/html/moodle/admin/tool/inactive_user_cleanup/classes/privacy/provider.php on line 29
`

`
Fatal error: Class tool_inactive_user_cleanup\privacy\provider contains 3 abstract methods and must therefore be declared abstract or implement the remaining methods (core_privacy\local\request\core_user_data_provider::get_contexts_for_userid, core_privacy\local\request\core_user_data_provider::export_user_data, core_privacy\local\request\core_userlist_provider::get_users_in_context) in /var/www/html/moodle/admin/tool/inactive_user_cleanup/classes/privacy/provider.php on line 40
`

/admin/tool/dataprivacy/pluginregistry.php

**Comment by moumitahalder** [comment]
Hi, we have added a fix on our end. 

Kindly download the plugin from here https://github.com/Jayanta7022/moodle-tool_inactive_user_cleanup/archive/refs/heads/master.zip and rename the plugin by removing the master tag. 

Then install this on your end, and check. 

The error should be resolved. Please do keep us posted.

**Comment by Snickser** [comment]
`Fatal error: Could not check compatibility between tool_inactive_user_cleanup\privacy\provider::get_metadata(tool_inactive_user_cleanup\privacy\collection $collection): tool_inactive_user_cleanup\privacy\collection and core_privacy\local\metadata\provider::get_metadata(core_privacy\local\metadata\collection $collection): core_privacy\local\metadata\collection, because class tool_inactive_user_cleanup\privacy\collection is not available in /var/www/html/moodle/admin/tool/inactive_user_cleanup/classes/privacy/provider.php on line 52`

**Comment by moumitahalder** [comment]
Hi @Snickser, we are not able to recreate this issue on our end. As you are still facing this issue can you please contact us over [here](https://dualcube.com/contact-us/), so we can assist you with this.

**Comment by Buda9** [comment]
> Your code breaks the page https://url/admin/tool/dataprivacy/pluginregistry.php

That's what I was trying to tell them [here](https://github.com/dualcube/moodle-tool_inactive_user_cleanup/pull/20)
