### ISSUE TITLE
Users who have never logged in are promptly deleted

### ISSUE THREAD

**Issue by mycodecrafting** [dualcube/moodle-tool_inactive_user_cleanup#3]
Users who have a `lastaccess` of 0 are immediately warned and deleted (if deletion is enabled) when the cron runs. There are a number of scenarios where a user would have a `lastaccess` of 0, for example, bulk user upload.

This plugin should ignore users who have never logged in, or perhaps better use `timecreated` if `lastaccess` is not available.

**Comment by kundandualcube** [comment]
it's solved and added in the latest version
