### ISSUE TITLE
Install not working: moodle PATH attribute does not match file directory

### ISSUE THREAD

**Issue by michaelpollak** [dualcube/moodle-tool_inactive_user_cleanup#5]
**Fix:** Change db/install.xml:2
<XMLDB PATH="admin/tool/inactive_user_cleanup/db" VERSION="20150420" COMMENT="XMLDB file for Moodle tool/inactive_user_cleanup"

Will check out the tool some more and maybe fork it to push some extensions.

**Comment by michaelpollak** [comment]
https://github.com/michaelpollak/moodle-tool_inactive_user_cleanup/blob/master/db/install.xml

Fixed and extended, thank you for your work.

**Comment by peterkeijsers** [comment]
I've created a pull-request for this problem: https://github.com/dualcube/moodle-tool_inactive_user_cleanup/pull/7

**Comment by kundandualcube** [comment]
it's solved and added in the latest version
